services:
  neogen.parser_manager:
    class: "Neoxygen\\Neogen\\Parser\\ParserManager"

  neogen.graph_generator:
    class: "Neoxygen\\Neogen\\GraphGenerator\\Generator"
    arguments: ["@neogen.graph_processor"]

  neogen.faker:
    class: "%faker.class%"

  neogen.graph_processor:
    class: "Neoxygen\\Neogen\\Processor\\GraphProcessor"
    arguments: ["@neogen.faker"]
